server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/digitest
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

user_bank:
  message:
    success: Account has been created successfully.
    fail: Account creation failed. Please contact your bank.
    hello: Hello